# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\GSReddy\PythonProjects\QT_Designer\fileProcessing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fileProcessing(object):
    def setupUi(self, fileProcessing):
        fileProcessing.setObjectName("fileProcessing")
        fileProcessing.setWindowModality(QtCore.Qt.ApplicationModal)
        fileProcessing.resize(944, 531)
        self.btnOptions = QtWidgets.QDialogButtonBox(fileProcessing)
        self.btnOptions.setGeometry(QtCore.QRect(510, 480, 411, 41))
        self.btnOptions.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnOptions.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btnOptions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnOptions.setOrientation(QtCore.Qt.Horizontal)
        self.btnOptions.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Open|QtWidgets.QDialogButtonBox.Save)
        self.btnOptions.setCenterButtons(False)
        self.btnOptions.setObjectName("btnOptions")
        self.btnSelectFiles = QtWidgets.QPushButton(fileProcessing)
        self.btnSelectFiles.setGeometry(QtCore.QRect(20, 60, 901, 31))
        self.btnSelectFiles.setFlat(False)
        self.btnSelectFiles.setObjectName("btnSelectFiles")
        self.tableWidget = QtWidgets.QTableWidget(fileProcessing)
        self.tableWidget.setGeometry(QtCore.QRect(20, 110, 901, 361))
        self.tableWidget.setMinimumSize(QtCore.QSize(661, 0))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)

        self.retranslateUi(fileProcessing)
        self.btnOptions.accepted.connect(fileProcessing.accept)
        self.btnOptions.rejected.connect(fileProcessing.reject)
        QtCore.QMetaObject.connectSlotsByName(fileProcessing)

    def retranslateUi(self, fileProcessing):
        _translate = QtCore.QCoreApplication.translate
        fileProcessing.setWindowTitle(_translate("fileProcessing", "Data File(s) Processing"))
        self.btnSelectFiles.setText(_translate("fileProcessing", "Select File(s)"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("fileProcessing", "File"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("fileProcessing", "Delimiter"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("fileProcessing", "No. of Rows"))
