DROP TABLE IF EXISTS APPLICANT;
DROP TABLE IF EXISTS ASSESMENT;
DROP TABLE IF EXISTS COLLEGES_APPLIED;
DROP TABLE IF EXISTS DEPENDENTS;
DROP TABLE IF EXISTS DOCUMENTS;
DROP TABLE IF EXISTS EDUCATION;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS ENROLLMENT;
DROP TABLE IF EXISTS FRANCHISE;
DROP TABLE IF EXISTS IDENTITIY;
DROP TABLE IF EXISTS PAYMENTS;
DROP TABLE IF EXISTS PROJECT_LOOKUP;
DROP TABLE IF EXISTS WORK_EXPERIENCE;

CREATE TABLE APPLICANT (
  APPLICATION_ID        VARCHAR(15) PRIMARY KEY, 
  APPLICATION_DATE      DATE NOT NULL, 
  FIRST_NAME            VARCHAR(100) NOT NULL, 
  LAST_NAME             VARCHAR(100) NOT NULL, 
  DATE_OF_BIRTH         DATE NOT NULL, 
  GENDER                CHAR(1) NOT NULL, 
  NATIONALITY           VARCHAR(25) NOT NULL, 
  FATHER_SPOUSE_NAME    VARCHAR(100) NOT NULL, 
  MOTHER_NAME           VARCHAR(100) NOT NULL, 
  MARITAL_STATUS        VARCHAR(30) NOT NULL, 
  MOBILE_NO             INT(10) NOT NULL, 
  EMAIL                 VARCHAR(100) NOT NULL, 
  ADDRESS               VARCHAR(1000) NOT NULL, 
  CITY                  VARCHAR(30) NOT NULL, 
  VILLAGE               VARCHAR(30), 
  MANDAL                VARCHAR(30), 
  DISTRICT              VARCHAR(30) NOT NULL, 
  STATE                 VARCHAR(30) NOT NULL, 
  COUNTRY               VARCHAR(30) NOT NULL, 
  PINCODE               INT(10) NOT NULL, 
  PHOTO                 BLOB, 
  REFERRED_BY           VARCHAR(10) NOT NULL, 
  APPLICATION_STATUS    VARCHAR(10) NOT NULL, 
  CREATED_BY            VARCHAR(10), 
  UPDATED_DATE			TIMESTAMP,
  APPLICATION_SOURCE_ID INT(10),
  APPLICATION_SUBMISSION_STATUS VARCHAR(10));
  
CREATE TABLE ASSESMENT (
  APPLICATION_ID    VARCHAR(15) NOT NULL, 
  ASSESSOR_ID       INT(10) NOT NULL, 
  ASSEMENT_DATE     TIMESTAMP, 
  ASSESSMENT_TYPE   INT(10) NOT NULL, 
  STATUS            VARCHAR(20) NOT NULL, 
  DOCUMENT_ID       VARCHAR(30), 
  PHOTO             BLOB, 
  ACTIVE            CHAR(1) NOT NULL, 
  COMMENTS          VARCHAR(1000) NOT NULL, 
  ASSESSOR_COMMENTS VARCHAR(1000) NOT NULL, 
  ASSEMENT_TYPE     INT(10) NOT NULL, 
  PRIMARY KEY (APPLICATION_ID));
  
CREATE TABLE COLLEGES_APPLIED (
  APPLICATION_ID     VARCHAR(15) NOT NULL, 
  COURSE_APPLIED     VARCHAR(100) NOT NULL, 
  COURSE_GROUP       VARCHAR(50) NOT NULL, 
  COURSE_BRANCH      VARCHAR(50) NOT NULL, 
  COLLEGE_APPLIED    VARCHAR(100) NOT NULL, 
  BOARD_UNIVERSITY   VARCHAR(100) NOT NULL, 
  LOCATION           VARCHAR(200) NOT NULL, 
  APPLICATION_STATUS VARCHAR(20) NOT NULL, 
  UPDATED_DATE	TIMESTAMP,
  PRIMARY KEY (APPLICATION_ID));
  
CREATE TABLE DEPENDENTS (
  APPLICATION_ID       VARCHAR(15) NOT NULL, 
  DEPENDENT_ID         VARCHAR(30) NOT NULL, 
  DEPENDENT_NAME       VARCHAR(100) NOT NULL, 
  RELATIONSHIP_TYPE_ID VARCHAR(20) NOT NULL, 
  DATE_OF_BIRTH        DATE NOT NULL, 
  COUNTRY              INT(10) NOT NULL, 
  DOCUMENT_IMAGE       BLOB NOT NULL, 
  PHONE                INT(15), 
  PRIMARY KEY (APPLICATION_ID));
  
CREATE TABLE DOCUMENTS (
  DOCUMENT_SOURCE_ID           VARCHAR(15) NOT NULL, 
  DOCUMENT_SOURCE              VARCHAR(20) NOT NULL, 
  DOCUMENT_FILE_TYPE           VARCHAR(50) NOT NULL, 
  DOCUMENT_UPLOADED_DATE       TIMESTAMP NOT NULL, 
  DOCUMENT                	   BLOB NOT NULL, 
  COMMENTS                     VARCHAR(1000) NOT NULL, 
  DOCUMENT_UPLOADED_BY         VARCHAR(15), 
  DOCUMENT_VERIFICATION_STATUS VARCHAR(15), 
  DOCUMENT_VERIFIED_BY         INT(10), 
  UPDATED_DATE					TIMESTAMP,
  DOCUMENT_ID                  VARCHAR(20));
  
CREATE TABLE EDUCATION (
  APPLICATION_ID         VARCHAR(15) NOT NULL, 
  COURSE_NAME            VARCHAR(100) NOT NULL, 
  COURSE_GROUP           VARCHAR(50) NOT NULL, 
  COURSE_BRANCH          VARCHAR(50) NOT NULL, 
  COURSE_START_DATE      DATE NOT NULL, 
  COURSE_COMPLETION_DATE DATE NOT NULL, 
  PERCENTAGE             DECIMAL(5, 2) NOT NULL, 
  INSTITUTION            VARCHAR(100) NOT NULL, 
  BOARD_UNIVERSITY       VARCHAR(100) NOT NULL, 
  GAP_DURATION_MONTHS    INT(3), 
  LOCATION               VARCHAR(200) NOT NULL, 
  DOCUMENT_ID            VARCHAR(20) NOT NULL, 
  UPDATED_DATE			 TIMESTAMP,
  PRIMARY KEY (APPLICATION_ID));
  
CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID  INT(10) NOT NULL AUTO_INCREMENT, 
  FIRST_NAME   VARCHAR(30) NOT NULL, 
  LAST_NAME    VARCHAR(30) NOT NULL, 
  DATE_OF_JOIN DATE NOT NULL, 
  DEPARTMENT   VARCHAR(10) NOT NULL, 
  DESIGNATION  VARCHAR(100) NOT NULL, 
  PHONE_NO     INT(15) NOT NULL, 
  EMAIL        VARCHAR(255) NOT NULL, 
  USER_ID      VARCHAR(10) NOT NULL, 
  PASSWORD     VARCHAR(10) NOT NULL, 
  LAST_LOGIN   TIMESTAMP, 
  ACTIVE       VARCHAR(10) NOT NULL, 
  AADHAAR_NO   INT(20) NOT NULL, 
  ADDRESS      INT(255) NOT NULL, 
  PHOTO        BLOB NOT NULL, 
  SALARY       DECIMAL(10, 2) NOT NULL, 
  PF_NO        VARCHAR(20) NOT NULL, 
  PAN_CARD     VARCHAR(10) NOT NULL, 
  BRANCH_CODE  VARCHAR(10) NOT NULL, 
  USER_TYPE    INT(10) NOT NULL, 
  MANAGER_ID   INT(10) NOT NULL, 
  PRIMARY KEY (EMPLOYEE_ID));
  
CREATE TABLE ENROLLMENT (
  APPLICATION_ID        VARCHAR(15) NOT NULL, 
  TRAINING_ID           VARCHAR(20) NOT NULL, 
  TRAINING_START_DATE   DATE NOT NULL, 
  TRAINING_END_DATE     DATE NOT NULL, 
  TRANING_DURATION      INT(10) NOT NULL, 
  LOCATION              VARCHAR(200) NOT NULL, 
  TRAINING_STATUS_ID    INT(10) NOT NULL, 
  TRAINING_TIME_BREAKUP VARCHAR(10) NOT NULL, 
  UPDATED_DATE			TIMESTAMP,
  PRIMARY KEY (APPLICATION_ID));
  
CREATE TABLE FRANCHISE (
  FRANCHISE_ID         VARCHAR(15) NOT NULL, 
  FRANCHISE_NAME       VARCHAR(100) NOT NULL, 
  MANAGER_ID           INT(10) NOT NULL, 
  FIRST_NAME           VARCHAR(30) NOT NULL, 
  LAST_NAME            VARCHAR(30) NOT NULL, 
  REGISTRATION_DATE    DATE NOT NULL, 
  PHONE_NO             INT(15) NOT NULL, 
  ALTERNATE_CONTACT_NO INT(10), 
  EMAIL                VARCHAR(255) NOT NULL, 
  DESIGNATION          VARCHAR(100) NOT NULL, 
  USER_ID              VARCHAR(10) NOT NULL, 
  PASSWORD             VARCHAR(10) NOT NULL, 
  LAST_LOGIN           TIMESTAMP NOT NULL, 
  ACTIVE               INT(10) NOT NULL, 
  AADHAAR_NO           INT(20) NOT NULL, 
  ADDRESS              INT(255) NOT NULL, 
  PHOTO                BLOB NOT NULL, 
  DOCUMENT_ID          INT(10) NOT NULL, 
  COMMISSION_AMOUNT    DECIMAL(10, 2) NOT NULL, 
  PAN_CARD             VARCHAR(10) NOT NULL, 
  GSTNO                VARCHAR(30) NOT NULL, 
  CITY                 INT(10) NOT NULL, 
  STATE                INT(10) NOT NULL, 
  COUNTRY              INT(10) NOT NULL, 
  PINCODE              INT(10) NOT NULL, 
  COMMENTS             VARCHAR(1000) NOT NULL, 
  PRIMARY KEY (FRANCHISE_ID));
  
CREATE TABLE IDENTITIY (
  APPLICATION_ID      VARCHAR(15) NOT NULL, 
  PROOF_OF_IDENTITY   VARCHAR(20) NOT NULL, 
  ID_NUMBER           VARCHAR(20) NOT NULL, 
  ISSUED_ORGANIZATION VARCHAR(100) NOT NULL, 
  START_DATE          DATE NOT NULL, 
  END_DATE            DATE NOT NULL, 
  PLACE_OF_ID_ISSUED  VARCHAR(100) NOT NULL, 
  COUNTRY             INT(10) NOT NULL, 
  DOCUMENT_IMAGE      BLOB NOT NULL, 
  PRIMARY KEY (APPLICATION_ID));
  
CREATE TABLE PAYMENTS (
  PAYMENT_DATE             DATE NOT NULL, 
  AMOUNT_PAID              DECIMAL(12, 2) NOT NULL, 
  MODE_OF_PAYMENT          VARCHAR(20) NOT NULL, 
  MODE_OF_PAYMENT_NO       VARCHAR(30) NOT NULL, 
  PAYMENT_REFERENCE_NO     INT(30) NOT NULL, 
  TRANSACTION_REFERENCE_NO VARCHAR(20) NOT NULL, 
  SGST                     INT(10) DEFAULT 0 NOT NULL, 
  IGST                     INT(10) DEFAULT 0 NOT NULL, 
  GSTNO                    VARCHAR(20) NOT NULL, 
  TRANSACTION_TYPE_ID      VARCHAR(20) NOT NULL, 
  APPLICATION_ID           VARCHAR(15) NOT NULL);
  
CREATE TABLE PROJECT_LOOKUP (
  LOOKUP_ID          VARCHAR(20) NOT NULL, 
  LOOKUP_CODE        VARCHAR(10) NOT NULL UNIQUE, 
  LOOKUP_TYPE        VARCHAR(10) NOT NULL UNIQUE, 
  LOOKUP_CATEGORY    VARCHAR(10) NOT NULL UNIQUE, 
  LOOKUP_NAME        VARCHAR(10) NOT NULL, 
  LOOKUP_DESCRIPTION VARCHAR(100) NOT NULL, 
  ACTIVE             CHAR(1) NOT NULL, 
  PRIMARY KEY (LOOKUP_ID));
  
CREATE TABLE WORK_EXPERIENCE (
  APPLICATION_ID          VARCHAR(15) NOT NULL, 
  COMPANY_NAME            VARCHAR(100) NOT NULL, 
  INDUSTRY_CATEGORY_ID    VARCHAR(20) NOT NULL, 
  DESIGNATION             VARCHAR(50) NOT NULL, 
  JOB_DESCRIPTION         VARCHAR(1000) NOT NULL, 
  TOTAL_EXPERIENCE_MONTHS INT(10) NOT NULL, 
  START_DATE              DATE NOT NULL, 
  END_DATE                DATE NOT NULL, 
  LOCATION                VARCHAR(100) NOT NULL, 
  UPDATED_DATE			  TIMESTAMP,
  COUNTRY                 INT(30) NOT NULL, 
  PRIMARY KEY (APPLICATION_ID));

ALTER TABLE EDUCATION ADD CONSTRAINT FK_APPLICANT_EDUCATION FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICANT (APPLICATION_ID);
ALTER TABLE WORK_EXPERIENCE ADD CONSTRAINT FK_APPLICANT_WRKEXPERIENCE FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICANT (APPLICATION_ID);
ALTER TABLE IDENTITIY ADD CONSTRAINT FK_APPLICANT_IDENTITY FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICANT (APPLICATION_ID);
ALTER TABLE DEPENDENTS ADD CONSTRAINT FK_APPLICANT_DEPENDENTS FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICANT (APPLICATION_ID);
ALTER TABLE COLLEGES_APPLIED ADD CONSTRAINT FK_APPLICANT_COLLEGES_APPLIED FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICANT (APPLICATION_ID);
ALTER TABLE ENROLLMENT ADD CONSTRAINT FK_APPLICANT_ENROLLMENT FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICANT (APPLICATION_ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_APPLICANT_DOCUMENTS FOREIGN KEY (DOCUMENT_SOURCE_ID) REFERENCES APPLICANT (APPLICATION_ID);
ALTER TABLE PAYMENTS ADD CONSTRAINT FK_APPLICANT_PAYMENTS FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICANT (APPLICATION_ID);
ALTER TABLE ASSESMENT ADD CONSTRAINT FK_APPLICANT_ASSESMENT FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICANT (APPLICATION_ID);

ALTER TABLE FRANCHISE ADD CONSTRAINT FK_FRANCHISE_ADMINEMP FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);
ALTER TABLE ASSESMENT ADD CONSTRAINT FK_ASSESMENT_ASSESSOR FOREIGN KEY (ASSESSOR_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_FRANCHISE_DOCUMENTSRC_LKP FOREIGN KEY (DOCUMENT_SOURCE_ID) REFERENCES FRANCHISE (FRANCHISE_ID);
ALTER TABLE ENROLLMENT ADD CONSTRAINT FK_APPLICANT_TRNGENROL_LKP FOREIGN KEY (TRAINING_ID) REFERENCES PROJECT_LOOKUP (LOOKUP_ID);
ALTER TABLE PAYMENTS ADD CONSTRAINT FK_PAYMENTS_TRANSTYP_LKP FOREIGN KEY (TRANSACTION_TYPE_ID) REFERENCES PROJECT_LOOKUP (LOOKUP_ID);
ALTER TABLE COLLEGES_APPLIED ADD CONSTRAINT FK_COLLEGESAPPLIED_LKP FOREIGN KEY (APPLICATION_STATUS) REFERENCES PROJECT_LOOKUP (LOOKUP_ID);
ALTER TABLE IDENTITIY ADD CONSTRAINT FK_IDENTITIY_LKP FOREIGN KEY (PROOF_OF_IDENTITY) REFERENCES PROJECT_LOOKUP (LOOKUP_ID);
ALTER TABLE DEPENDENTS ADD CONSTRAINT FK_DEPENDENTS_LKP FOREIGN KEY (RELATIONSHIP_TYPE_ID) REFERENCES PROJECT_LOOKUP (LOOKUP_ID);
ALTER TABLE WORK_EXPERIENCE ADD CONSTRAINT FK_WORKEXP_LKP FOREIGN KEY (INDUSTRY_CATEGORY_ID) REFERENCES PROJECT_LOOKUP (LOOKUP_ID);


SELECT APPLICATION_ID, APPLICATION_DATE, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, GENDER, NATIONALITY, FATHER_SPOUSE_NAME, MOTHER_NAME, MARITAL_STATUS, MOBILE_NO, EMAIL, ADDRESS, CITY, VILLAGE, MANDAL, DISTRICT, STATE, COUNTRY, PINCODE, PHOTO, REFERRED_BY, APPLICATION_STATUS, CREATED_BY, APPLICATION_SOURCE_ID 
  FROM APPLICANT;
SELECT APPLICATION_ID, ASSESSOR_ID, ASSEMENT_DATE, ASSESSMENT_TYPE, STATUS, DOCUMENT_ID, IMAGE, ACTIVE, COMMENTS, ASSESSOR_COMMENTS, ASSEMENT_TYPE 
  FROM ASSESMENT;
SELECT APPLICATION_ID, COURSE_APPLIED, COURSE_GROUP, COURSE_BRANCH, COLLEGE_APPLIED, BOARD_UNIVERSITY, LOCATION, APPLICATION_STATUS 
  FROM COLLEGES_APPLIED;
SELECT APPLICATION_ID, DEPENDENT_ID, DEPENDENT_NAME, RELATIONSHIP_TYPE_ID, DATE_OF_BIRTH, COUNTRY, DOCUMENT_IMAGE, PHONE 
  FROM DEPENDENTS;
SELECT DOCUMENT_SOURCE_ID, DOCUMENT_SOURCE, DOCUMENT_FILE_TYPE, DOCUMENT_UPLOADED_DATE, DOCUMENT_FILE, COMMENTS, DOCUMENT_UPLOADED_BY, DOCUMENT_VERIFICATION_STATUS, DOCUMENT_VERIFIED_BY, DOCUMENT_ID 
  FROM DOCUMENTS;
SELECT APPLICATION_ID, COURSE_NAME, COURSE_GROUP, COURSE_BRANCH, COURSE_START_DATE, COURSE_COMPLETION_DATE, PERCENTAGE, INSTITUTION, BOARD_UNIVERSITY, GAP_DURATION_MONTHS, LOCATION, DOCUMENT_ID 
  FROM EDUCATION;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DATE_OF_JOIN, DEPARTMENT, DESIGNATION, PHONE_NO, EMAIL, USER_ID, PASSWORD, LAST_LOGIN, ACTIVE, AADHAAR_NO, ADDRESS, PHOTO, SALARY, PF_NO, PAN_CARD, BRANCH_CODE, USER_TYPE, MANAGER_ID 
  FROM EMPLOYEE;
SELECT APPLICATION_ID, TRAINING_ID, TRAINING_START_DATE, TRAINING_END_DATE, TRANING_DURATION, LOCATION, TRAINING_STATUS_ID, TRAINING_TIME_BREAKUP 
  FROM ENROLLMENT;
SELECT FRANCHISE_ID, FRANCHISE_NAME, MANAGER_ID, FIRST_NAME, LAST_NAME, REGISTRATION_DATE, PHONE_NO, ALTERNATE_CONTACT_NO, EMAIL, DESIGNATION, USER_ID, PASSWORD, LAST_LOGIN, ACTIVE, AADHAAR_NO, ADDRESS, PHOTO, DOCUMENT_ID, COMMISSION_AMOUNT, PAN_CARD, GSTNO, CITY, STATE, COUNTRY, PINCODE, COMMENTS 
  FROM FRANCHISE;
SELECT APPLICATION_ID, PROOF_OF_IDENTITY, ID_NUMBER, ISSUED_ORGANIZATION, START_DATE, END_DATE, PLACE_OF_ID_ISSUED, COUNTRY, DOCUMENT_IMAGE 
  FROM IDENTITIY;
SELECT PAYMENT_DATE, AMOUNT_PAID, MODE_OF_PAYMENT, MODE_OF_PAYMENT_NO, PAYMENT_REFERENCE_NO, TRANSACTION_REFERENCE_NO, SGST, IGST, GSTNO, TRANSACTION_TYPE_ID, APPLICATION_ID 
  FROM PAYMENTS;
SELECT LOOKUP_ID, LOOKUP_CODE, LOOKUP_TYPE, LOOKUP_CATEGORY, LOOKUP_NAME, LOOKUP_DESCRIPTION, ACTIVE 
  FROM PROJECT_LOOKUP;
SELECT APPLICATION_ID, COMPANY_NAME, INDUSTRY_CATEGORY_ID, DESIGNATION, JOB_DESCRIPTION, TOTAL_EXPERIENCE_MONTHS, START_DATE, END_DATE, LOCATION, COUNTRY 
  FROM WORK_EXPERIENCE;

INSERT INTO APPLICANT
  (APPLICATION_ID, 
  APPLICATION_DATE, 
  FIRST_NAME, 
  LAST_NAME, 
  DATE_OF_BIRTH, 
  GENDER, 
  NATIONALITY, 
  FATHER_SPOUSE_NAME, 
  MOTHER_NAME, 
  MARITAL_STATUS, 
  MOBILE_NO, 
  EMAIL, 
  ADDRESS, 
  CITY, 
  VILLAGE, 
  MANDAL, 
  DISTRICT, 
  STATE, 
  COUNTRY, 
  PINCODE, 
  PHOTO, 
  REFERRED_BY, 
  APPLICATION_STATUS, 
  CREATED_BY, 
  APPLICATION_SOURCE_ID) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO ASSESMENT
  (APPLICATION_ID, 
  ASSESSOR_ID, 
  ASSEMENT_DATE, 
  ASSESSMENT_TYPE, 
  STATUS, 
  DOCUMENT_ID, 
  IMAGE, 
  ACTIVE, 
  COMMENTS, 
  ASSESSOR_COMMENTS, 
  ASSEMENT_TYPE) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO COLLEGES_APPLIED
  (APPLICATION_ID, 
  COURSE_APPLIED, 
  COURSE_GROUP, 
  COURSE_BRANCH, 
  COLLEGE_APPLIED, 
  BOARD_UNIVERSITY, 
  LOCATION, 
  APPLICATION_STATUS) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO DEPENDENTS
  (APPLICATION_ID, 
  DEPENDENT_ID, 
  DEPENDENT_NAME, 
  RELATIONSHIP_TYPE_ID, 
  DATE_OF_BIRTH, 
  COUNTRY, 
  DOCUMENT_IMAGE, 
  PHONE) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO DOCUMENTS
  (DOCUMENT_SOURCE_ID, 
  DOCUMENT_SOURCE, 
  DOCUMENT_FILE_TYPE, 
  DOCUMENT_UPLOADED_DATE, 
  DOCUMENT_FILE, 
  COMMENTS, 
  DOCUMENT_UPLOADED_BY, 
  DOCUMENT_VERIFICATION_STATUS, 
  DOCUMENT_VERIFIED_BY, 
  DOCUMENT_ID) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO EDUCATION
  (APPLICATION_ID, 
  COURSE_NAME, 
  COURSE_GROUP, 
  COURSE_BRANCH, 
  COURSE_START_DATE, 
  COURSE_COMPLETION_DATE, 
  PERCENTAGE, 
  INSTITUTION, 
  BOARD_UNIVERSITY, 
  GAP_DURATION_MONTHS, 
  LOCATION, 
  DOCUMENT_ID) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO EMPLOYEE
  (EMPLOYEE_ID, 
  FIRST_NAME, 
  LAST_NAME, 
  DATE_OF_JOIN, 
  DEPARTMENT, 
  DESIGNATION, 
  PHONE_NO, 
  EMAIL, 
  USER_ID, 
  PASSWORD, 
  LAST_LOGIN, 
  ACTIVE, 
  AADHAAR_NO, 
  ADDRESS, 
  PHOTO, 
  SALARY, 
  PF_NO, 
  PAN_CARD, 
  BRANCH_CODE, 
  USER_TYPE, 
  MANAGER_ID) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO ENROLLMENT
  (APPLICATION_ID, 
  TRAINING_ID, 
  TRAINING_START_DATE, 
  TRAINING_END_DATE, 
  TRANING_DURATION, 
  LOCATION, 
  TRAINING_STATUS_ID, 
  TRAINING_TIME_BREAKUP) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO FRANCHISE
  (FRANCHISE_ID, 
  FRANCHISE_NAME, 
  MANAGER_ID, 
  FIRST_NAME, 
  LAST_NAME, 
  REGISTRATION_DATE, 
  PHONE_NO, 
  ALTERNATE_CONTACT_NO, 
  EMAIL, 
  DESIGNATION, 
  USER_ID, 
  PASSWORD, 
  LAST_LOGIN, 
  ACTIVE, 
  AADHAAR_NO, 
  ADDRESS, 
  PHOTO, 
  DOCUMENT_ID, 
  COMMISSION_AMOUNT, 
  PAN_CARD, 
  GSTNO, 
  CITY, 
  STATE, 
  COUNTRY, 
  PINCODE, 
  COMMENTS) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO IDENTITIY
  (APPLICATION_ID, 
  PROOF_OF_IDENTITY, 
  ID_NUMBER, 
  ISSUED_ORGANIZATION, 
  START_DATE, 
  END_DATE, 
  PLACE_OF_ID_ISSUED, 
  COUNTRY, 
  DOCUMENT_IMAGE) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO PAYMENTS
  (PAYMENT_DATE, 
  AMOUNT_PAID, 
  MODE_OF_PAYMENT, 
  MODE_OF_PAYMENT_NO, 
  PAYMENT_REFERENCE_NO, 
  TRANSACTION_REFERENCE_NO, 
  SGST, 
  IGST, 
  GSTNO, 
  TRANSACTION_TYPE_ID, 
  APPLICATION_ID) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO PROJECT_LOOKUP
  (LOOKUP_ID, 
  LOOKUP_CODE, 
  LOOKUP_TYPE, 
  LOOKUP_CATEGORY, 
  LOOKUP_NAME, 
  LOOKUP_DESCRIPTION, 
  ACTIVE) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);
INSERT INTO WORK_EXPERIENCE
  (APPLICATION_ID, 
  COMPANY_NAME, 
  INDUSTRY_CATEGORY_ID, 
  DESIGNATION, 
  JOB_DESCRIPTION, 
  TOTAL_EXPERIENCE_MONTHS, 
  START_DATE, 
  END_DATE, 
  LOCATION, 
  COUNTRY) 
VALUES 
  (?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?, 
  ?);

UPDATE APPLICANT SET 
  APPLICATION_ID = ?, 
  APPLICATION_DATE = ?, 
  FIRST_NAME = ?, 
  LAST_NAME = ?, 
  DATE_OF_BIRTH = ?, 
  GENDER = ?, 
  NATIONALITY = ?, 
  FATHER_SPOUSE_NAME = ?, 
  MOTHER_NAME = ?, 
  MARITAL_STATUS = ?, 
  MOBILE_NO = ?, 
  EMAIL = ?, 
  ADDRESS = ?, 
  CITY = ?, 
  VILLAGE = ?, 
  MANDAL = ?, 
  DISTRICT = ?, 
  STATE = ?, 
  COUNTRY = ?, 
  PINCODE = ?, 
  PHOTO = ?, 
  REFERRED_BY = ?, 
  APPLICATION_STATUS = ?, 
  CREATED_BY = ?, 
  APPLICATION_SOURCE_ID = ? 
WHERE
  ;
UPDATE ASSESMENT SET 
  ASSESSOR_ID = ?, 
  ASSEMENT_DATE = ?, 
  ASSESSMENT_TYPE = ?, 
  STATUS = ?, 
  DOCUMENT_ID = ?, 
  IMAGE = ?, 
  ACTIVE = ?, 
  COMMENTS = ?, 
  ASSESSOR_COMMENTS = ?, 
  ASSEMENT_TYPE = ? 
WHERE
  APPLICATION_ID = ?;
UPDATE COLLEGES_APPLIED SET 
  COURSE_APPLIED = ?, 
  COURSE_GROUP = ?, 
  COURSE_BRANCH = ?, 
  COLLEGE_APPLIED = ?, 
  BOARD_UNIVERSITY = ?, 
  LOCATION = ?, 
  APPLICATION_STATUS = ? 
WHERE
  APPLICATION_ID = ?;
UPDATE DEPENDENTS SET 
  DEPENDENT_ID = ?, 
  DEPENDENT_NAME = ?, 
  RELATIONSHIP_TYPE_ID = ?, 
  DATE_OF_BIRTH = ?, 
  COUNTRY = ?, 
  DOCUMENT_IMAGE = ?, 
  PHONE = ? 
WHERE
  APPLICATION_ID = ?;
UPDATE DOCUMENTS SET 
  DOCUMENT_SOURCE_ID = ?, 
  DOCUMENT_SOURCE = ?, 
  DOCUMENT_FILE_TYPE = ?, 
  DOCUMENT_UPLOADED_DATE = ?, 
  DOCUMENT_FILE = ?, 
  COMMENTS = ?, 
  DOCUMENT_UPLOADED_BY = ?, 
  DOCUMENT_VERIFICATION_STATUS = ?, 
  DOCUMENT_VERIFIED_BY = ?, 
  DOCUMENT_ID = ? 
WHERE
  ;
UPDATE EDUCATION SET 
  COURSE_NAME = ?, 
  COURSE_GROUP = ?, 
  COURSE_BRANCH = ?, 
  COURSE_START_DATE = ?, 
  COURSE_COMPLETION_DATE = ?, 
  PERCENTAGE = ?, 
  INSTITUTION = ?, 
  BOARD_UNIVERSITY = ?, 
  GAP_DURATION_MONTHS = ?, 
  LOCATION = ?, 
  DOCUMENT_ID = ? 
WHERE
  APPLICATION_ID = ?;
UPDATE EMPLOYEE SET 
  FIRST_NAME = ?, 
  LAST_NAME = ?, 
  DATE_OF_JOIN = ?, 
  DEPARTMENT = ?, 
  DESIGNATION = ?, 
  PHONE_NO = ?, 
  EMAIL = ?, 
  USER_ID = ?, 
  PASSWORD = ?, 
  LAST_LOGIN = ?, 
  ACTIVE = ?, 
  AADHAAR_NO = ?, 
  ADDRESS = ?, 
  PHOTO = ?, 
  SALARY = ?, 
  PF_NO = ?, 
  PAN_CARD = ?, 
  BRANCH_CODE = ?, 
  USER_TYPE = ?, 
  MANAGER_ID = ? 
WHERE
  EMPLOYEE_ID = ?;
UPDATE ENROLLMENT SET 
  TRAINING_ID = ?, 
  TRAINING_START_DATE = ?, 
  TRAINING_END_DATE = ?, 
  TRANING_DURATION = ?, 
  LOCATION = ?, 
  TRAINING_STATUS_ID = ?, 
  TRAINING_TIME_BREAKUP = ? 
WHERE
  APPLICATION_ID = ?;
UPDATE FRANCHISE SET 
  FRANCHISE_NAME = ?, 
  MANAGER_ID = ?, 
  FIRST_NAME = ?, 
  LAST_NAME = ?, 
  REGISTRATION_DATE = ?, 
  PHONE_NO = ?, 
  ALTERNATE_CONTACT_NO = ?, 
  EMAIL = ?, 
  DESIGNATION = ?, 
  USER_ID = ?, 
  PASSWORD = ?, 
  LAST_LOGIN = ?, 
  ACTIVE = ?, 
  AADHAAR_NO = ?, 
  ADDRESS = ?, 
  PHOTO = ?, 
  DOCUMENT_ID = ?, 
  COMMISSION_AMOUNT = ?, 
  PAN_CARD = ?, 
  GSTNO = ?, 
  CITY = ?, 
  STATE = ?, 
  COUNTRY = ?, 
  PINCODE = ?, 
  COMMENTS = ? 
WHERE
  FRANCHISE_ID = ?;
UPDATE IDENTITIY SET 
  PROOF_OF_IDENTITY = ?, 
  ID_NUMBER = ?, 
  ISSUED_ORGANIZATION = ?, 
  START_DATE = ?, 
  END_DATE = ?, 
  PLACE_OF_ID_ISSUED = ?, 
  COUNTRY = ?, 
  DOCUMENT_IMAGE = ? 
WHERE
  APPLICATION_ID = ?;
UPDATE PAYMENTS SET 
  PAYMENT_DATE = ?, 
  AMOUNT_PAID = ?, 
  MODE_OF_PAYMENT = ?, 
  MODE_OF_PAYMENT_NO = ?, 
  PAYMENT_REFERENCE_NO = ?, 
  TRANSACTION_REFERENCE_NO = ?, 
  SGST = ?, 
  IGST = ?, 
  GSTNO = ?, 
  TRANSACTION_TYPE_ID = ?, 
  APPLICATION_ID = ? 
WHERE
  ;
UPDATE PROJECT_LOOKUP SET 
  LOOKUP_CODE = ?, 
  LOOKUP_TYPE = ?, 
  LOOKUP_CATEGORY = ?, 
  LOOKUP_NAME = ?, 
  LOOKUP_DESCRIPTION = ?, 
  ACTIVE = ? 
WHERE
  LOOKUP_ID = ?;
UPDATE WORK_EXPERIENCE SET 
  COMPANY_NAME = ?, 
  INDUSTRY_CATEGORY_ID = ?, 
  DESIGNATION = ?, 
  JOB_DESCRIPTION = ?, 
  TOTAL_EXPERIENCE_MONTHS = ?, 
  START_DATE = ?, 
  END_DATE = ?, 
  LOCATION = ?, 
  COUNTRY = ? 
WHERE
  APPLICATION_ID = ?;

DELETE FROM APPLICANT 
  WHERE ;
DELETE FROM ASSESMENT 
  WHERE APPLICATION_ID = ?;
DELETE FROM COLLEGES_APPLIED 
  WHERE APPLICATION_ID = ?;
DELETE FROM DEPENDENTS 
  WHERE APPLICATION_ID = ?;
DELETE FROM DOCUMENTS 
  WHERE ;
DELETE FROM EDUCATION 
  WHERE APPLICATION_ID = ?;
DELETE FROM EMPLOYEE 
  WHERE EMPLOYEE_ID = ?;
DELETE FROM ENROLLMENT 
  WHERE APPLICATION_ID = ?;
DELETE FROM FRANCHISE 
  WHERE FRANCHISE_ID = ?;
DELETE FROM IDENTITIY 
  WHERE APPLICATION_ID = ?;
DELETE FROM PAYMENTS 
  WHERE ;
DELETE FROM PROJECT_LOOKUP 
  WHERE LOOKUP_ID = ?;
DELETE FROM WORK_EXPERIENCE 
  WHERE APPLICATION_ID = ?;

