DROP TABLE IF EXISTS APPLICANT;
DROP TABLE IF EXISTS ASSESMENT;
DROP TABLE IF EXISTS COLLEGES_APPLIED;
DROP TABLE IF EXISTS DEPENDENTS;
DROP TABLE IF EXISTS DOCUMENTS;
DROP TABLE IF EXISTS EDUCATION;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS ENROLLMENT;
DROP TABLE IF EXISTS FRANCHISE;
DROP TABLE IF EXISTS IDENTITIY;
DROP TABLE IF EXISTS PAYMENTS;
DROP TABLE IF EXISTS PROJECT_LOOKUP;
DROP TABLE IF EXISTS WORK_EXPERIENCE;

CREATE TABLE APPLICANT (
  APPLICATION_ID        varchar(15) NOT NULL, 
  Application_Date      date NOT NULL, 
  First_Name            varchar(100) NOT NULL, 
  Last_Name             varchar(100) NOT NULL, 
  Date_Of_Birth         date NOT NULL, 
  Gender                char(1) NOT NULL, 
  Nationality           varchar(25) NOT NULL, 
  Father_Spouse_Name    varchar(100) NOT NULL, 
  Mother_Name           varchar(100) NOT NULL, 
  Marital_Status        varchar(30) NOT NULL, 
  Mobile_No             integer(10) NOT NULL, 
  EMail                 varchar(100) NOT NULL, 
  Address               varchar(1000) NOT NULL, 
  City                  varchar(30) NOT NULL, 
  Village               varchar(30), 
  Mandal                varchar(30), 
  District              varchar(30) NOT NULL, 
  State                 varchar(30) NOT NULL, 
  Country               varchar(30) NOT NULL, 
  PinCode               integer(10) NOT NULL, 
  Photo                 blob NOT NULL, 
  Referred_By           varchar(10) NOT NULL, 
  Application_Status    varchar(10) NOT NULL, 
  Created_By            integer(10), 
  Application_Source_ID integer(10));
CREATE TABLE ASSESMENT (
  APPLICATION_ID    varchar(15) NOT NULL, 
  ASSESSOR_ID       integer(10) NOT NULL, 
  Assement_Date     date NOT NULL, 
  Assessment_Type   integer(10) NOT NULL, 
  Status            varchar(20) NOT NULL, 
  Document_ID       varchar(30), 
  Image             blob NOT NULL, 
  Active            char(1) NOT NULL, 
  Comments          varchar(1000) NOT NULL, 
  Assessor_Comments varchar(1000) NOT NULL, 
  Assement_Type     integer(10) NOT NULL, 
  PRIMARY KEY (APPLICATION_ID), 
  FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICANT(APPLICATION_ID), 
  FOREIGN KEY(ASSESSOR_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID), 
  FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICANT(APPLICATION_ID));
CREATE TABLE COLLEGES_APPLIED (
  APPLICATION_ID     varchar(15) NOT NULL, 
  Course_Applied     varchar(100) NOT NULL, 
  Course_Group       varchar(50) NOT NULL, 
  Course_Branch      varchar(50) NOT NULL, 
  College_Applied    varchar(100) NOT NULL, 
  Board_University   varchar(100) NOT NULL, 
  Location           varchar(200) NOT NULL, 
  Application_Status varchar(20) NOT NULL, 
  PRIMARY KEY (APPLICATION_ID), 
  FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICANT(APPLICATION_ID), 
  FOREIGN KEY(Application_Status) REFERENCES PROJECT_LOOKUP(LOOKUP_ID));
CREATE TABLE DEPENDENTS (
  APPLICATION_ID       varchar(15) NOT NULL, 
  Dependent_ID         varchar(30) NOT NULL, 
  Dependent_Name       varchar(100) NOT NULL, 
  RELATIONSHIP_TYPE_ID varchar(20) NOT NULL, 
  Date_Of_Birth        date NOT NULL, 
  Country              integer(10) NOT NULL, 
  Document_Image       blob NOT NULL, 
  Phone                integer(15), 
  PRIMARY KEY (APPLICATION_ID), 
  FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICANT(APPLICATION_ID), 
  FOREIGN KEY(RELATIONSHIP_TYPE_ID) REFERENCES PROJECT_LOOKUP(LOOKUP_ID));
CREATE TABLE DOCUMENTS (
  DOCUMENT_SOURCE_ID           varchar(15) NOT NULL, 
  Document_Source              varchar(20) NOT NULL, 
  Document_File_Type           varchar(50) NOT NULL, 
  Document_Uploaded_Date       timestamp NOT NULL, 
  Document_File                blob NOT NULL, 
  Comments                     varchar(1000) NOT NULL, 
  Document_Uploaded_By         varchar(15), 
  Document_Verification_Status varchar(15), 
  Document_Verified_By         integer(10), 
  DOCUMENT_ID                  varchar(20), 
  FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICANT(APPLICATION_ID), 
  FOREIGN KEY(DOCUMENT_SOURCE_ID) REFERENCES FRANCHISE(FRANCHISE_ID));
CREATE TABLE EDUCATION (
  APPLICATION_ID         varchar(15) NOT NULL, 
  Course_Name            varchar(100) NOT NULL, 
  Course_Group           varchar(50) NOT NULL, 
  Course_Branch          varchar(50) NOT NULL, 
  Course_Start_Date      date NOT NULL, 
  Course_Completion_Date date NOT NULL, 
  Percentage             numeric(5, 2) NOT NULL, 
  Institution            varchar(100) NOT NULL, 
  Board_University       varchar(100) NOT NULL, 
  Gap_Duration_Months    integer(3), 
  Location               varchar(200) NOT NULL, 
  DOCUMENT_ID            varchar(20) NOT NULL, 
  PRIMARY KEY (APPLICATION_ID), 
  FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICANT(APPLICATION_ID));
CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  FIRST_NAME   varchar(30) NOT NULL, 
  LAST_NAME    varchar(30) NOT NULL, 
  DATE_OF_JOIN date NOT NULL, 
  DEPARTMENT   varchar(10) NOT NULL, 
  DESIGNATION  varchar(100) NOT NULL, 
  PHONE_NO     integer(15) NOT NULL, 
  EMAIL        varchar(255) NOT NULL, 
  USER_ID      varchar(10) NOT NULL, 
  PASSWORD     varchar(10) NOT NULL, 
  LAST_LOGIN   timestamp NOT NULL, 
  ACTIVE       varchar(10) NOT NULL, 
  AADHAAR_NO   integer(20) NOT NULL, 
  ADDRESS      integer(255) NOT NULL, 
  PHOTO        blob NOT NULL, 
  SALARY       numeric(10, 2) NOT NULL, 
  PF_NO        varchar(20) NOT NULL, 
  PAN_CARD     varchar(10) NOT NULL, 
  BRANCH_CODE  varchar(10) NOT NULL, 
  USER_TYPE    integer(10) NOT NULL, 
  MANAGER_ID   integer(10) NOT NULL);
CREATE TABLE ENROLLMENT (
  APPLICATION_ID        varchar(15) NOT NULL, 
  TRAINING_ID           varchar(20) NOT NULL, 
  Training_Start_Date   date NOT NULL, 
  Training_End_Date     date NOT NULL, 
  Traning_Duration      integer(10) NOT NULL, 
  Location              varchar(200) NOT NULL, 
  Training_Status_ID    integer(10) NOT NULL, 
  Training_Time_Breakup varchar(10) NOT NULL, 
  PRIMARY KEY (APPLICATION_ID), 
  FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICANT(APPLICATION_ID), 
  FOREIGN KEY(TRAINING_ID) REFERENCES PROJECT_LOOKUP(LOOKUP_ID));
CREATE TABLE FRANCHISE (
  FRANCHISE_ID         varchar(15) NOT NULL, 
  FRANCHISE_NAME       varchar(100) NOT NULL, 
  MANAGER_ID           integer(10) NOT NULL, 
  FIRST_NAME           varchar(30) NOT NULL, 
  LAST_NAME            varchar(30) NOT NULL, 
  REGISTRATION_DATE    date NOT NULL, 
  PHONE_NO             integer(15) NOT NULL, 
  ALTERNATE_CONTACT_NO integer(10), 
  EMAIL                varchar(255) NOT NULL, 
  DESIGNATION          varchar(100) NOT NULL, 
  USER_ID              varchar(10) NOT NULL, 
  PASSWORD             varchar(10) NOT NULL, 
  LAST_LOGIN           timestamp NOT NULL, 
  ACTIVE               integer(10) NOT NULL, 
  AADHAAR_NO           integer(20) NOT NULL, 
  ADDRESS              integer(255) NOT NULL, 
  PHOTO                blob NOT NULL, 
  DOCUMENT_ID          integer(10) NOT NULL, 
  COMMISSION_AMOUNT    numeric(10, 2) NOT NULL, 
  PAN_CARD             varchar(10) NOT NULL, 
  GSTNO                varchar(30) NOT NULL, 
  CITY                 integer(10) NOT NULL, 
  STATE                integer(10) NOT NULL, 
  COUNTRY              integer(10) NOT NULL, 
  PINCODE              integer(10) NOT NULL, 
  Comments             varchar(1000) NOT NULL, 
  PRIMARY KEY (FRANCHISE_ID), 
  FOREIGN KEY(MANAGER_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID));
CREATE TABLE IDENTITIY (
  APPLICATION_ID      varchar(15) NOT NULL, 
  Proof_Of_Identity   varchar(20) NOT NULL, 
  ID_Number           varchar(20) NOT NULL, 
  Issued_Organization varchar(100) NOT NULL, 
  Start_Date          date NOT NULL, 
  End_Date            date NOT NULL, 
  Place_Of_ID_Issued  varchar(100) NOT NULL, 
  Country             integer(10) NOT NULL, 
  Document_Image      blob NOT NULL, 
  PRIMARY KEY (APPLICATION_ID), 
  FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICANT(APPLICATION_ID), 
  FOREIGN KEY(Proof_Of_Identity) REFERENCES PROJECT_LOOKUP(LOOKUP_ID));
CREATE TABLE PAYMENTS (
  PAYMENT_DATE             date NOT NULL, 
  AMOUNT_PAID              numeric(12, 2) NOT NULL, 
  MODE_OF_PAYMENT          varchar(20) NOT NULL, 
  MODE_OF_PAYMENT_NO       varchar(30) NOT NULL, 
  PAYMENT_REFERENCE_NO     integer(30) NOT NULL, 
  TRANSACTION_REFERENCE_NO varchar(20) NOT NULL, 
  SGST                     integer(10) DEFAULT 0 NOT NULL, 
  IGST                     integer(10) DEFAULT 0 NOT NULL, 
  GSTNO                    varchar(20) NOT NULL, 
  TRANSACTION_TYPE_ID      varchar(20) NOT NULL, 
  APPLICATION_ID           varchar(15) NOT NULL, 
  FOREIGN KEY(TRANSACTION_TYPE_ID) REFERENCES PROJECT_LOOKUP(LOOKUP_ID), 
  FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICANT(APPLICATION_ID));
CREATE TABLE PROJECT_LOOKUP (
  LOOKUP_ID          varchar(20) NOT NULL, 
  LOOKUP_CODE        varchar(10) NOT NULL UNIQUE, 
  LOOKUP_TYPE        varchar(10) NOT NULL UNIQUE, 
  LOOKUP_CATEGORY    varchar(10) NOT NULL UNIQUE, 
  LOOKUP_NAME        varchar(10) NOT NULL, 
  LOOKUP_DESCRIPTION varchar(100) NOT NULL, 
  ACTIVE             char(1) NOT NULL, 
  PRIMARY KEY (LOOKUP_ID));
CREATE TABLE WORK_EXPERIENCE (
  APPLICATION_ID          varchar(15) NOT NULL, 
  Company_Name            varchar(100) NOT NULL, 
  INDUSTRY_CATEGORY_ID    varchar(20) NOT NULL, 
  Designation             varchar(50) NOT NULL, 
  Job_Description         varchar(1000) NOT NULL, 
  Total_Experience_Months integer(10) NOT NULL, 
  Start_Date              date NOT NULL, 
  End_Date                date NOT NULL, 
  Location                varchar(100) NOT NULL, 
  Country                 integer(30) DEFAULT INDIA NOT NULL, 
  PRIMARY KEY (APPLICATION_ID), 
  FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICANT(APPLICATION_ID), 
  FOREIGN KEY(INDUSTRY_CATEGORY_ID) REFERENCES PROJECT_LOOKUP(LOOKUP_ID));

