DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS ORDER_DETAIL;
DROP TABLE IF EXISTS ORDERS_HEADER;
DROP TABLE IF EXISTS PAYMENTS;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PROJECT_LOOKUP;
DROP TABLE IF EXISTS SUPPLIER;

